[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "gn_module_connectors"
description = "Module GeoNature d'alimentation de la Synthèse depuis des sources externes (GBIF, VisioNature)"
readme = "README.md"
authors = [{ name = "ANA-CEN Ariège" }]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU Affero General Public License v3",
  "Operating System :: OS Independent",
]
dynamic = ["version", "dependencies"]

[project.entry-points.gn_module]
code = "gn_module_connectors:MODULE_CODE"
picto = "gn_module_connectors:MODULE_PICTO"
blueprint = "gn_module_connectors.blueprint:blueprint"
config_schema = "gn_module_connectors.conf_schema_toml:GnModuleSchemaConf"
migrations = "gn_module_connectors:migrations"
tasks = "gn_module_connectors.tasks"

[tool.setuptools]
package-dir = { "" = "backend" }

[tool.setuptools.packages.find]
where = ["backend"]

[tool.setuptools.dynamic]
version = { file = "VERSION" }
dependencies = { file = "requirements.in" }
